try {
    print("The code below throws an error")
    const foo = "foo";
    foo = "bar"
    print("this will not get printed")
} catch {
    print("Error occurred, exception thrown")
}
